const building = require('../enum/building');
const ward = require('../enum/ward');

module.exports = {
    [ward.ADMINISTRATION]: [
        building.ADMIN,
        building.ASYLUM,
        building.BATH_HOUSE,
        building.BATH,
        building.CEMETERY,
        building.CISTERN,
        building.FOUNTAIN,
        building.GRANARY,
        building.GUILD_HALL,
        building.HOSPITAL,
        building.HOUSE,
        building.INN,
        building.LIBRARY,
        building.OFFICE,
        building.PLAZA,
        building.PRISON,
        building.RELIGIOUS,
        building.SHOP,
        building.STABLE,
        building.TAVERN,
        building.WAREHOUSE,
        building.WELL,
        building.WORKSHOP,
    ],

    [ward.CRAFTSMEN]: [
        building.ADMIN,
        building.BATH_HOUSE,
        building.BATH,
        building.CISTERN,
        building.FOUNTAIN,
        building.GUILD_HALL,
        building.HOSPITAL,
        building.HOUSE,
        building.RELIGIOUS,
        building.SHOP,
        building.TAVERN,
        building.TENEMENT,
        building.THEATER,
        building.WAREHOUSE,
        building.WELL,
        building.WORKSHOP,
    ],

    [ward.GATE]: [
        building.ADMIN,
        building.BATH_HOUSE,
        building.BATH,
        building.CORRAL,
        building.FOUNTAIN,
        building.HOSPITAL,
        building.HOUSE,
        building.INN,
        building.OFFICE,
        building.RELIGIOUS,
        building.SHOP,
        building.STABLE,
        building.TAVERN,
        building.WAREHOUSE,
        building.WELL,
        building.WORKSHOP,
    ],

    [ward.LAYOUT_EMPTY]: [],

    [ward.MARKET]: [
        building.ADMIN,
        building.BATH,
        building.CISTERN,
        building.FOUNTAIN,
        building.GRANARY,
        building.GUILD_HALL,
        building.HOUSE,
        building.INN,
        building.OFFICE,
        building.PLAZA,
        building.RELIGIOUS,
        building.SHOP,
        building.STABLE,
        building.TAVERN,
        building.WAREHOUSE,
        building.WELL,
    ],

    [ward.MERCHANT]: [
        building.ADMIN,
        building.BATH_HOUSE,
        building.BATH,
        building.CEMETERY,
        building.CISTERN,
        building.FOUNTAIN,
        building.GARDEN,
        building.GRANARY,
        building.GUILD_HALL,
        building.HOSPITAL,
        building.HOUSE,
        building.INN,
        building.LIBRARY,
        building.OFFICE,
        building.PLAZA,
        building.RELIGIOUS,
        building.REST,
        building.SHOP,
        building.STABLE,
        building.TAVERN,
        building.UNIVERSITY,
        building.WAREHOUSE,
        building.WELL,
        building.WORKSHOP,
    ],

    [ward.MILITARY]: [
        building.ADMIN,
        building.BARRACK,
        building.BATH,
        building.COLISEUM,
        building.CORRAL,
        building.FOUNTAIN,
        building.GRANARY,
        building.HOUSE,
        building.INFIRMARY,
        building.PRISON,
        building.RELIGIOUS,
        building.SHOP,
        building.STABLE,
        building.TAVERN,
        building.WAREHOUSE,
        building.WELL,
        building.WORKSHOP,
    ],

    [ward.ODORIFEROUS]: [
        building.ADMIN,
        building.BATH,
        building.CEMETERY,
        building.CORRAL,
        building.FOUNTAIN,
        building.HOSPITAL,
        building.HOUSE,
        building.INN,
        building.RELIGIOUS,
        building.SHOP,
        building.TAVERN,
        building.TENEMENT,
        building.WAREHOUSE,
        building.WELL,
        building.WORKSHOP,
    ],

    [ward.PATRICIATE]: [
        building.ADMIN,
        building.BATH_HOUSE,
        building.BATH,
        building.CEMETERY,
        building.CISTERN,
        building.FOUNTAIN,
        building.GARDEN,
        building.GRANARY,
        building.HOSPITAL,
        building.HOUSE,
        building.INN,
        building.LIBRARY,
        building.OFFICE,
        building.PLAZA,
        building.RELIGIOUS,
        building.RESTAURANT,
        building.SHOP,
        building.STABLE,
        building.TAVERN,
        building.UNIVERSITY,
        building.WAREHOUSE,
        building.WELL,
    ],

    [ward.RIVER]: [
        building.ADMIN,
        building.BATH_HOUSE,
        building.BATH,
        building.CORRAL,
        building.FOUNTAIN,
        building.GRANARY,
        building.HOUSE,
        building.INN,
        building.MILL,
        building.OFFICE,
        building.RELIGIOUS,
        building.SHOP,
        building.TENEMENT,
        building.WELL,
        building.WORKSHOP,
    ],

    [ward.SEA]: [
        building.ADMIN,
        building.BATH_HOUSE,
        building.BATH,
        building.CORRAL,
        building.FOUNTAIN,
        building.GRANARY,
        building.HOUSE,
        building.INN,
        building.MILL,
        building.OFFICE,
        building.RELIGIOUS,
        building.SHOP,
        building.TENEMENT,
        building.WELL,
        building.WORKSHOP,
    ],

    [ward.SHANTY]: [
        building.FOUNTAIN,
        building.HOUSE,
        building.TAVERN,
        building.WELL,
        building.WORKSHOP,
    ],

    [ward.SLUM]: [
        building.ADMIN,
        building.BATH,
        building.CEMETERY,
        building.FOUNTAIN,
        building.HOSPITAL,
        building.HOUSE,
        building.INN,
        building.RELIGIOUS,
        building.SHOP,
        building.TAVERN,
        building.TENEMENT,
        building.WAREHOUSE,
        building.WELL,
        building.WORKSHOP,
    ],
};
