const populationType = require('../../src/enum/populationType');
const ward = require('../../src/enum/ward');

module.exports = {
    [populationType.THORP]: {
        [ward.PATRICIATE]: 1,
        [ward.MERCHANT]: 1,
        [ward.MILITARY]: 1,
        [ward.ADMINISTRATION]: 1,
        [ward.ODORIFEROUS]: 2,
        [ward.CRAFTSMEN]: 2,
        [ward.SEA]: 2,
        [ward.RIVER]: 2,
        [ward.MARKET]: 3,
        [ward.GATE]: 3,
        [ward.SLUM]: 3,
        [ward.SHANTY]: 3,
    },
    [populationType.HAMLET]: {
        [ward.PATRICIATE]: 4,
        [ward.MERCHANT]: 4,
        [ward.MILITARY]: 4,
        [ward.ADMINISTRATION]: 5,
        [ward.ODORIFEROUS]: 5,
        [ward.CRAFTSMEN]: 5,
        [ward.SEA]: 6,
        [ward.RIVER]: 6,
        [ward.MARKET]: 7,
        [ward.GATE]: 7,
        [ward.SLUM]: 8,
        [ward.SHANTY]: 8,
    },
    [populationType.VILLAGE]: {
        [ward.PATRICIATE]: 9,
        [ward.MERCHANT]: 9,
        [ward.MILITARY]: 10,
        [ward.ADMINISTRATION]: 10,
        [ward.ODORIFEROUS]: 11,
        [ward.CRAFTSMEN]: 11,
        [ward.SEA]: 12,
        [ward.RIVER]: 12,
        [ward.MARKET]: 13,
        [ward.GATE]: 13,
        [ward.SLUM]: 14,
        [ward.SHANTY]: 14,
    },
    [populationType.SMALL_TOWN]: {
        [ward.PATRICIATE]: 15,
        [ward.MERCHANT]: 15,
        [ward.MILITARY]: 15,
        [ward.ADMINISTRATION]: 16,
        [ward.ODORIFEROUS]: 16,
        [ward.CRAFTSMEN]: 16,
        [ward.SEA]: 17,
        [ward.RIVER]: 17,
        [ward.MARKET]: 18,
        [ward.GATE]: 18,
        [ward.SLUM]: 19,
        [ward.SHANTY]: 19,
    },
    [populationType.LARGE_TOWN]: {
        [ward.PATRICIATE]: 29,
        [ward.MERCHANT]: 21,
        [ward.MILITARY]: 22,
        [ward.ADMINISTRATION]: 23,
        [ward.ODORIFEROUS]: 24,
        [ward.CRAFTSMEN]: 25,
        [ward.SEA]: 26,
        [ward.RIVER]: 27,
        [ward.MARKET]: 28,
        [ward.GATE]: 28,
        [ward.SLUM]: 29,
        [ward.SHANTY]: 29,
    },
    [populationType.SMALL_CITY]: {
        [ward.PATRICIATE]: 39,
        [ward.MERCHANT]: 41,
        [ward.MILITARY]: 43,
        [ward.ADMINISTRATION]: 45,
        [ward.ODORIFEROUS]: 47,
        [ward.CRAFTSMEN]: 49,
        [ward.SEA]: 51,
        [ward.RIVER]: 53,
        [ward.MARKET]: 55,
        [ward.GATE]: 57,
        [ward.SLUM]: 59,
        [ward.SHANTY]: 61,
    },
    [populationType.LARGE_CITY]: {
        [ward.PATRICIATE]: 50,
        [ward.MERCHANT]: 52,
        [ward.MILITARY]: 54,
        [ward.ADMINISTRATION]: 56,
        [ward.ODORIFEROUS]: 58,
        [ward.CRAFTSMEN]: 60,
        [ward.SEA]: 62,
        [ward.RIVER]: 63,
        [ward.MARKET]: 64,
        [ward.GATE]: 66,
        [ward.SLUM]: 68,
        [ward.SHANTY]: 69,
    },
    [populationType.METROPOLIS]: {
        [ward.PATRICIATE]: 60,
        [ward.MERCHANT]: 62,
        [ward.MILITARY]: 64,
        [ward.ADMINISTRATION]: 66,
        [ward.ODORIFEROUS]: 68,
        [ward.CRAFTSMEN]: 70,
        [ward.SEA]: 72,
        [ward.RIVER]: 74,
        [ward.MARKET]: 76,
        [ward.GATE]: 78,
        [ward.SLUM]: 80,
        [ward.SHANTY]: 80,
    },
};
