module.exports = {
    ADMIN: 'Admin',
    ASYLUM: 'Asylum',
    BATH_HOUSE: 'Bath House',
    BARRACK: 'Barrack',
    BATH: 'Bath',
    CEMETERY: 'Cemetery',
    CISTERN: 'Cistern',
    COLISEUM: 'Coliseum',
    CORRAL: 'Corral',
    FOUNTAIN: 'Fountain',
    GARDEN: 'Garden',
    GRANARY: 'Granary',
    GUILD_HALL: 'Guild House',
    HOSPITAL: 'Hospital',
    HOUSE: 'House',
    INFIRMARY: 'Infirmary',
    INN: 'Inn',
    LIBRARY: 'Library',
    MILL: 'Mill',
    OFFICE: 'Office',
    PLAZA: 'Plaza',
    PRISON: 'Prison',
    RELIGIOUS: 'Religious',
    REST: 'Rest',
    RESTAURANT: 'Restaurant',
    SHOP: 'Shop',
    STABLE: 'Stable',
    TAVERN: 'Tavern',
    TENEMENT: 'Tenement',
    THEATER: 'Theater',
    UNIVERSITY: 'University',
    WAREHOUSE: 'Warehouse',
    WELL: 'Well',
    WORKSHOP: 'Workshop',
};
