module.exports = {
    ARCHITECTS_ENGINEERS: 'Architects & Engineers',
    ARMORERS_LOCKSMITHS: 'Armorers & Locksmiths',
    ARTISTS: 'Artists',
    BAKERS: 'Bakers',
    BOOKBINDERS_PAPER_MAKERS: 'Bookbinders & Paper Makers',
    BOWYERS_FLETCHERS: 'Bowyers & Fletchers',
    BREWERS_DISTILLERS_VINTNERS: 'Brewers, Distillers, & Vintners',
    BROTHEL_KEEPERS: 'Brothel Keepers',
    BUILDERS: 'Builders',
    BUTCHERS: 'Butchers',
    CASTERS: 'Casters',
    CHANDLERS: 'Chandlers',
    CLAY_STONE_WORKERS: 'Clay & Stone Workers',
    CLERKS_SCRIBES: 'Clerks & Scribes',
    CLOTHING_ACCESSORIES: 'Clothing & Accessories',
    COBBLERS: 'Cobblers',
    COOPERS: 'Coopers',
    CORDWAINERS: 'Cordwainers',
    DYERS_WEAVERS: 'Dyers & Weavers',
    FINANCIAL_TRANSACTIONS: 'Financial Transactions',
    FISHMONGERS: 'Fishmongers',
    FORGERS_SMITHS: 'Forgers & Smiths',
    FURRIERS: 'Furriers',
    GLASS_WORKERS: 'Glass Workers',
    HARNESS_MAKERS_SADDLERS: 'Harness Makers & Saddlers',
    HOSTLIERS: 'Hostliers',
    JEWELERS: 'Jewelers',
    LAUNDERERS: 'Launderers',
    MAGIC: 'Magic',
    MAP_MAKERS_SURVEYORS: 'Map Makers & Surveyors',
    MARINERS: 'Mariners',
    MEDICAL: 'Medical',
    MERCHANTS: 'Merchants',
    MUSIC_PERFORMERS: 'Music & Performers',
    PROFESSIONAL_GUILDS: 'Professional Guilds',
    SCHOLASTIC: 'Scholastic',
    SHIPWRIGHTS: 'Shipwrights',
    SKINNERS_TANNERS: 'Skinners & Tanners',
    STABLE_KEEPERS: 'Stable Keepers',
    TINKERERS: 'Tinkerers',
    WATER_MEN: 'Water Men',
    WHEEL_WRIGHTS: 'Wheel Wrights',
    WICKER_WORKERS: 'Wicker Workers',
    WOOD_WORKERS: 'Wood Workers',
};
