module.exports = {
    ADEPT: 'Adept',
    ARISTOCRAT: 'Aristocrat',
    BARBARIAN: 'Barbarian',
    BARD: 'Bard',
    CLERIC: 'Cleric',
    COMMONER: 'Commoner',
    DRUID: 'Druid',
    EXPERT: 'Expert',
    FIGHTER: 'Fighter',
    MONK: 'Monk',
    MONSTER: 'Monster',
    PALADIN: 'Paladin',
    PSIONIC: 'Psionic',
    RANGER: 'Ranger',
    ROGUE: 'Rogue',
    SORCERER: 'Sorcerer',
    WARRIOR: 'Warrior',
    WIZARD: 'Wizard',
};
