module.exports = {
    ACROBATS_TUMBLERS: 'Acrobats & Tumblers',
    ADVOCATES_LAWYERS: 'Advocates (lawyers)',
    ALCHEMISTS: 'Alchemists',
    APPRENTICES: 'Apprentices',
    ARCHITECTS: 'Architects',
    ARMORERS: 'Armorers',
    ARTISTS: 'Artists',
    ASTROLOGERS: 'Astrologers',
    BAKERS: 'Bakers',
    BANKERS: 'Bankers',
    BARBERS: 'Barbers',
    BASKET_MAKERS: 'Basket Makers',
    BATHERS: 'Bathers',
    BEER_MERCHANTS: 'Beer Merchants',
    BEGGARS: 'Beggars',
    BELL_MAKERS: 'Bell Makers',
    BLACKSMITHS: 'Blacksmiths',
    BLEACHERS: 'Bleachers',
    BOOKBINDERS: 'Bookbinders',
    BOOKSELLERS: 'Booksellers',
    BOWYER_FLETCHERS: 'Bowyer/Fletchers',
    BREWERS: 'Brewers',
    BRICKLAYERS: 'Bricklayers',
    BROTHEL_KEEPERS: 'Brothel Keepers',
    BUCKLE_MAKERS: 'Buckle Makers',
    BUTCHERS: 'Butchers',
    CARAVANNER: 'Caravanner',
    CARPENTERS: 'Carpenters',
    CARTOGRAPHERS: 'Cartographers',
    CHANDLERS: 'Chandlers',
    CLERGY_MEMBERS: 'Clergy Members',
    CLOCK_MAKERS: 'Clock Makers',
    CLOTHIERS_USED: 'Clothiers & Used',
    COBBLERS: 'Cobblers',
    COOKS: 'Cooks',
    COOPERS: 'Coopers',
    COPYISTS: 'Copyists',
    CUTLERS: 'Cutlers',
    DAIRY_SELLERS: 'Dairy Sellers',
    DENTISTS: 'Dentists',
    DIPLOMATS: 'Diplomats',
    DISTILLERS: 'Distillers',
    DOCTORS_LICENSED: 'Doctors & Licensed',
    DOCTORS_UNLICENSED: 'Doctors & Unlicensed',
    DOMESTIC_SERVANTS: 'Domestic Servants',
    DRAPERS: 'Drapers',
    DYE_MAKERS: 'Dye Makers',
    ELDERLY_INFIRM: 'Elderly/Infirm',
    ENGINEERS: 'Engineers',
    ENGRAVERS: 'Engravers',
    FISHERS: 'Fishers',
    FISHMONGERS: 'Fishmongers',
    FLOWER_SELLERS: 'Flower Sellers',
    FULLERS: 'Fullers',
    FURNITURE_MAKERS: 'Furniture Makers',
    FURRIERS: 'Furriers',
    GARDENERS: 'Gardeners',
    GIRDLERS: 'Girdlers',
    GLASS_MAKERS: 'Glass Makers',
    GLAZIERS: 'Glaziers',
    GLOVE_MAKERS: 'Glove Makers',
    GOLDSMITHS: 'Goldsmiths',
    GRAIN_MERCHANTS: 'Grain Merchants',
    GROCERS: 'Grocers',
    GROOMS: 'Grooms',
    GUARDS_CITY_GOVERNMENTAL: 'Guards (City & Governmental)',
    GUARDS_PRIVATE: 'Guards (Private)',
    GUIDES_TOUTS: 'Guides/Touts',
    HABERDASHERS: 'Haberdashers',
    HARNESS_MAKERS: 'Harness Makers',
    HAY_MERCHANTS: 'Hay Merchants',
    HERBALISTS: 'Herbalists',
    HISTORIANS: 'Historians',
    HOUSEWIVES_HOUSEHUSBANDS: 'Housewives & Househusbands',
    ILLUMINATORS: 'Illuminators',
    INN_KEEPERS: 'Inn Keepers',
    INSTRUMENT_MAKERS: 'Instrument Makers',
    INVENTORS: 'Inventors',
    JESTERS: 'Jesters',
    JEWELERS: 'Jewelers',
    JONGLEURS: 'Jongleurs',
    JOURNEYMEN: 'Journeymen',
    JUDGES: 'Judges',
    LABORERS: 'Laborers',
    LAUNDERERS: 'Launderers',
    LEATHER_WORKERS: 'Leather Workers',
    LIBRARIANS: 'Librarians',
    LIVESTOCK_MERCHANTS: 'Livestock Merchants',
    LOCKSMITHS: 'Locksmiths',
    MAGIC_MERCHANTS: 'Magic Merchants',
    MASONS: 'Masons',
    MENDICANTS: 'Mendicants',
    MERCENARIES: 'Mercenaries',
    MERCERS: 'Mercers',
    MIDWIVES: 'Midwives',
    MILLERS: 'Millers',
    MINSTRELS: 'Minstrels',
    MONEYCHANGERS: 'Moneychangers',
    NANNIES_GOVERNESSES: 'Nannies & Governesses',
    NAVEL_OUTFITTERS: 'Navel Outfitters',
    NAVIGATORS_PATHFINDERS: 'Navigators/Pathfinders',
    OFFICIALS: 'Officials',
    PAGES: 'Pages',
    PAINTERS: 'Painters',
    PAPER_PARCHMENT_MAKERS: 'Paper/Parchment Makers',
    PASTRY_MAKERS: 'Pastry Makers',
    PAWNBROKER: 'Pawnbroker',
    PEDDLERS: 'Peddlers',
    PERFUMER: 'Perfumer',
    PLASTERERS: 'Plasterers',
    PORTERS: 'Porters',
    POTION_MAKERS: 'Potion Makers',
    POTTERS: 'Potters',
    PROFESSORS: 'Professors',
    PROSTITUTES: 'Prostitutes',
    PURSE_MAKERS: 'Purse Makers',
    RAT_CATCHERS: 'Rat Catchers',
    RELIGIOUS_SOUVENIR_SELLERS: 'Religious Souvenir Sellers',
    RESTAURATEURS: 'Restaurateurs',
    ROOFERS: 'Roofers',
    ROPE_MAKERS: 'Rope Makers',
    RUG_MAKERS: 'Rug Makers',
    SADDLERS_SPURRIERS: 'Saddlers & Spurriers',
    SAGE_SCHOLAR: 'Sage/Scholar',
    SAILORS: 'Sailors',
    SATIRISTS: 'Satirists',
    SCABBARD_MAKERS: 'Scabbard Makers',
    SCULPTORS: 'Sculptors',
    SERVERS: 'Servers (Taverns, Inns, Restaurants)',
    SHIP_MAKERS: 'Ship Makers',
    SILVERSMITHS: 'Silversmiths',
    SKINNERS: 'Skinners',
    SLAVERS: 'Slavers',
    SLAVES: 'Slaves',
    SOAP_MAKERS: 'Soap Makers',
    SPICE_MERCHANTS: 'Spice Merchants',
    STORYTELLERS: 'Storytellers',
    STUDENTS: 'Students',
    TAILORS: 'Tailors',
    TANNERS: 'Tanners',
    TAVERN_KEEPERS: 'Tavern Keepers',
    TAX_COLLECTORS: 'Tax Collectors',
    TAXIDERMISTS: 'Taxidermists',
    TEACHERS: 'Teachers',
    THIEVES: 'Thieves',
    TILERS: 'Tilers',
    TINKERS: 'Tinkers',
    TOBACCO_MERCHANTS: 'Tobacco Merchants',
    TOWN_CRIERS: 'Town Criers',
    TOY_MAKERS: 'Toy Makers',
    TRAVELER: 'Traveler',
    UNDERTAKERS: 'Undertakers',
    VESTMENT_MAKERS: 'Vestment Makers',
    VINTNER: 'Vintner',
    WAREHOUSERS: 'Warehousers',
    WATER_CARRIERS: 'Water Carriers',
    WEAPON_SMITHS: 'Weapon Smiths',
    WEAVERS: 'Weavers',
    WET_NURSES: 'Wet Nurses',
    WHEELWRIGHTS: 'Wheelwrights',
    WINE_MERCHANTS: 'Wine Merchants',
    WOOD_SELLERS: 'Wood Sellers',
    WOODCARVERS: 'Woodcarvers',
    WRITERS: 'Writers',
    WOOL_MERCHANTS: 'Wool Merchants',
};
